const projectsList = [
  // {
  //   title: "DerHaus - Portfolio",
  //   description: "Portfolio of a swiss architect",
  //   techs: "ReactJS",
  //   link: "https://derhaus.ch",
  //   img: "/img/018.png",
  //   // id: "01",
  //   // format: "1",
  // },
  {
    title: "FRATELLI - E Commerce Store",
    description: "Turkish Figs and Chocolates",
    techs: "ReactJS, NodeJs, MongoDB",
    link: "https://fratelli.vercel.app",
    img: "/img/018.png",
    // id: "01",
    // format: "1",
  },
  {
    title: "Beverix - E Commerce Store",
    description: "Beverage selling online store",
    techs: "ReactJS, NodeJS, MongoDB",
    link: "https://beverix.vercel.app",
    img: "/img/010.png",
    // id: "03",
    // format: "1",
  },
  {
    title: "Beverix - Native App",
    description: "Beverage selling app for IOS and Android",
    techs: "React Native, NodeJs, MongoDB",
    link: "https://expo.io/@aqibasif/projects/Beverix?release-channel=staging",
    img: "/img/004.png",
    // id: "02",
    // format: "2",
  },
  {
    title: "MESSIX - WEBSITE",
    description: "Basic messaging website",
    techs: "ReactJS, NodeJs, MongoDB",
    link: "https://messix.vercel.app",
    img: "/img/014.png",
    // id: "04",
    // format: "2",
  },
  {
    title: "Omega - website",
    description: "Sanitary fittings",
    techs: "ReactJS",
    link: "https://omegasanitary.vercel.app",
    img: "/img/007.png",
    // id: "05",
    // format: "1",
  },
  {
    title: "Portfolio - Website",
    description: "Project Gallery",
    techs: "ReactJS",
    link: "https://aqibasif.herokuapp.com",
    img: "/img/006.png",
    // id: "06",
    // format: "2",
  },
  {
    title: "VERk - e commerce store",
    description: "Swedish watches",
    techs: "ReactJS, NodeJS, MongoDB",
    link: "https://verk-store.herokuapp.com",
    img: "/img/002.png",
    // id: "07",
    // format: "1",
  },
];

export default projectsList;
